# -*- coding: utf-8 -*-
"""tony_thor_cap_GULBAHAR_ELMAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ax3Bf018mbUm5NgR3eClDhaiyhSs9Zd_
"""

import random

def tony_thor_cap_GULBAHAR_ELMAS():
      #Here I wrote the characters in a list.
    characters = ["Thor", "Cap", "Tony"]

    #Here I wrote a dictionary to store the game rules.
    game_rules = {
        ("Thor", "Cap"): "Thor defeats Cap.",
        ("Cap", "Tony"): "Cap defeats Tony.",
        ("Tony", "Thor"): "Tony defeats Thor."
    }

        #This part is beginning of the game.
    def print_welcome_message():
        print("**********************************************************************************************************************")
        print("Welcome to Marvel World!")
        print("**********************************************************************************************************************")
        print("Choose a character to fight against the computer. The one who gets to 2 points first will win the match.")


        #Here I explained the rules to the player.
        print("The rules:")
        for (char1, char2), result in game_rules.items():
            print(f"- {result}")                    #Here I used f-string for better readability.
        print("\nReady to start? (yes/no)")


        # Here I get the choice of player.
    def get_player_choice():
        while True:
            choice = input("Choose your character (Thor, Cap, Tony): ").capitalize()  # I used capitalize() function to convert the first character of the input string to uppercase and the rest to lowercase.
            if choice in characters:
                return choice
            else:
                print("Invalid choice. Please choose 'Thor', 'Cap', or 'Tony'.")    #If player writes wrong words, I warn the player.

        #Here I get computer choice randomly with random.choice function.
    def get_computer_choice():
        return random.choice(characters)


        # This function determines the winner.
    def determine_winner(player_choice, computer_choice):
        if player_choice == computer_choice:   #If the choices are same, It will be tie.
            return "Tie"
        elif (player_choice, computer_choice) in game_rules:
            return "Player"
        else:
            return "Computer"


    def play_round():
        player_score = 0             # This variable is for counting the score of player.
        computer_score = 0           # This variable is for counting the score of computer.

        while player_score < 2 and computer_score < 2:
            print("\nNew Round Starting!")
            player_choice = get_player_choice()
            computer_choice = get_computer_choice()

            print(f"Computer's choice: {computer_choice}")

            result = determine_winner(player_choice, computer_choice)

            if result == "Player":
                player_score += 1
                print("\nYou won this round!")
            elif result == "Computer":
                computer_score += 1
                print("\nComputer won this round! You lost!")
            else:
                print("This round is a tie!")

            print("\n******************************************************************")
            print(f"Current Score - Player: {player_score}, Computer: {computer_score}")        #After every round, I explain the scores to the player.
            print("******************************************************************")

        if player_score == 2:       #Here If the player gets 2 points, user will. In other case computer win.
            print("\n*************************** Congratulations! You won the game! ***************************")
        else:
            print("\n*************************** Computer won the game! ***************************")


        #Here I ask to the player if he/she wants to continue the game.
    def ask_to_continue():
        while True:
            choice = input("\nWould you like to play again? (yes/no): ").strip().lower()    # I used strip() function to remove whitespace characters, and lower() function to convert input string to lowercase.
            if choice == "yes":
                return True
            elif choice == "no":
                print("The battle is over.Until our next fight! Goodbye!!")
                return False
            else:
                print("Invalid choice. Please enter 'yes' or 'no'.")                       #If player writes wrong words, I warn the player.

    print_welcome_message()
    start_game = input().strip().lower()

    if start_game == "yes":
        while True:
            play_round()
            if not ask_to_continue():         # If player doesnt want to continue the game, ask_to_continue return 0, and "not 0" is 1. So game will be end with break statement.
                break
    else:
        print("Goodbye!")

tony_thor_cap_GULBAHAR_ELMAS()

